### ISSUE TITLE
401

### ISSUE THREAD

**Issue by e3c8f1a924** [ouuan/LuoguPaintBoard#1]
如题

我把自己的Cookie正确地书写在了cookies.json里，但每次Post都会返回401，提示没有登录。

**Comment by e3c8f1a924** [comment]
![image](https://user-images.githubusercontent.com/46619411/71619768-e9104080-2c00-11ea-9682-12821fd2e88f.png)

**Comment by e3c8f1a924** [comment]
@ouuan

**Comment by ouuan** [comment]
您可能在获取 Cookies 后退出登录了。建议使用浏览器的无痕窗口获取 Cookies，在不退出的情况下关闭无痕窗口即可使 Cookie 保持登录状态。

**Comment by e3c8f1a924** [comment]
> 您可能在获取 Cookies 后退出登录了。建议使用浏览器的无痕窗口获取 Cookies，在不退出的情况下关闭无痕窗口即可使 Cookie 保持登录状态。

我试试

谢谢

**Comment by e3c8f1a924** [comment]
还是一样
![image](https://user-images.githubusercontent.com/46619411/71622237-51661e80-2c0f-11ea-91a9-b46af944c324.png)

**Comment by e3c8f1a924** [comment]
@ouuan 是不是洛谷后台改动过了......

**Comment by e3c8f1a924** [comment]
__client_id拼错了......
